#!/usr/bin/env bash

set -eo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT_DIR="$( cd ${DIR}/.. && pwd )"

export PYTHONPATH="${PYTHONPATH}:$DIR/src"
exec arq saturn_engine.worker.executors.arq.worker.WorkerSettings
