---
apiVersion: saturn.flared.io/v1alpha1
kind: SaturnExecutor
metadata:
  name: default
spec:
  type: ProcessExecutor
  options:
    max_workers: 1
---
apiVersion: saturn.flared.io/v1alpha1
kind: SaturnExecutor
metadata:
  name: pooled
spec:
  type: ProcessExecutor
  options:
    max_workers: 4
