#!/usr/bin/env python
import asyncio
import aio_pika
import sys


def main():
    if len(sys.argv) != 4:
        print(f"{sys.argv[0]} url queue_name message")
        sys.exit(1)

    url = sys.argv[1]
    queue_name = sys.argv[2]
    message = sys.argv[3]

    async def main_task():
        connection = await aio_pika.connect_robust(url)

        async with connection:
            channel = await connection.channel()

            await channel.default_exchange.publish(
                aio_pika.Message(body=message.encode()),
                routing_key=queue_name,
            )

    asyncio.run(main_task())


if __name__ == "__main__":
    main()
